"""email verifiction

Revision ID: 73f0f963659e
Revises: b40de3da0154
Create Date: 2026-08-03 11:53:58.357003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73f0f963659e"
down_revision: Union[str, Sequence[str], None] = "b40de3da0154"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_is_verified", sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_is_verified")
    # ### end Alembic commands ###
